"""
# DO NOT EDIT THIS FILE #
"""
import pygame as pg
from .vec2 import Vec2
from .transform import Transform
from .world import World
from .sprite import Sprite
from .sound_manager import SoundManager
from .physic_sprite import PhysicSprite
from .input_manager import InputManager
from .game_object import GameObject
import os
import asyncio


os.environ['PYGAME_HIDE_SUPPORT_PROMPT'] = '1'

pg.init()
try:
    pg.mixer.init()
except:
    print('Failed to initialize Mixer')

try:
    pg.font.init()
except Exception as e:
    print('Failed to initialize Font')


class TitoEngine:
    def __init__(self, win_title: str = 'Tito Engine Game', win_resolution: tuple[int, int] | None = None, colour_fill: tuple[int, int, int] = (255, 255, 255), fps: int = 60):
        pg.display.set_caption(win_title)

        info = pg.display.Info()
        self.WIN = pg.display.set_mode(win_resolution if win_resolution else (
            info.current_w, info.current_h), pg.SCALED, pg.FULLSCREEN)
        self.CLOCK = pg.time.Clock()
        self.FPS = fps
        self.COLOUR_FILL = colour_fill

        self.initialized = True
        print('Tito Engine Initialized Successfully')

    def run(self, game_objects: list[GameObject] = []):
        asyncio.run(self._run(game_objects))

    async def _run(self, game_objects: list[GameObject] = []):
        self.world = World(self.WIN, game_objects)

        running = True

        # Main Loop
        while running:
            # Updating window
            DT = self.CLOCK.tick(self.FPS) / 1000.0
            self.WIN.fill(self.COLOUR_FILL)
            self.world.update(DT)

            # Close Window when 'X' pressed
            for event in pg.event.get():
                if event.type == pg.QUIT:
                    pg.quit()
                    running = False
                    return 0

            pg.display.update()
            await asyncio.sleep(0)
